name: Build Docker images (ARM64)

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:

    - name: Install Compose
      uses: ndeloof/install-compose-action@v0.0.1
      with:
        version: v2.1.0 # defaults to 'latest'
        legacy: true    # will also install in PATH as `docker-compose`

    - uses: actions/checkout@v3

    - name: Build NF's images
      run: ./script/build.sh aarch64
